<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Promise</title>
  </head>
  <body>
    <script>
      /* Promise 객체 : 처리에 성공 시 실행할 콜백 함수,
                          실패 시 실행할 콜백 함수 
                          위 2가지를 미리 약속
      */
     // 활용 사례 : 공공 API 로 특정한 시간에 js 를 실행해 data 를 DB 에 insert 가능
     // Promise 객체를 사용할 수 밖에 없다

      // resolve : 성공 시 실행
      // reject : 실패 시 실행

      // Producer & Consumer
      // Producer 입장
      // Promise 객체 생성
      const promise = new Promise((resolve, reject) => {
        setTimeout(() => {
          // resolve("성공");
          reject(new Error("실패")); // Error 객체에 담아줌
        }, 2000);
      });

      // consumer 입장 : promise 사용자 관점
      // then : 실행 성공 시 작동
      // catch() : 실행 실패 시 작동
      // finally() : 무조건 마지막에 작동하는 함수
      promise
        .then((response) => {
          console.log(response);
        })
        .catch((err) => {
          console.log(err);
        })
        .finally(() => {
          console.log("최종");
        });

      // promise 체이닝
      const fetchNumber = new Promise((res, rej) => {
        setTimeout(() => res(1), 1000);
      });
      // then() 영역에는 value 뿐만 아니라 promise 객체도 전달 가능
      fetchNumber
        .then((num) => num * 2)
        .then((num) => num * 3)
        .then((num) => {
          return new Promise((res, rej) => {
            setTimeout(() => res(num), 1000);
          });
        })
        .then((res) => {
          console.log(res);
        });

      /* error 핸들링 */
      const getHen = () => {
        return new Promise((res, rej) => {
          setTimeout(() => res("🐓"), 1000);
        });
      };

      const getEgg = (hen) => {
        return new Promise((res, rej) => {
          setTimeout(() => res(`${hen} => '🥚'`), 1000);
        // setTimeout(() => rej(`error! ${hen} => '🥚'`), 1000);
        });
      };

      const getCook = (egg) => {
        return new Promise((res, rej) => {
          setTimeout(() => res(`${egg} => '🍳'`), 1000);
        });
      };

      getHen()
        .then((hen) => getEgg(hen)).catch((err) => {
            console.log(err);
            return "🐙"
        })
        .then((egg) => getCook(egg))
        .then((meal) => console.log(meal)).catch()

        // 중간에 error 가 발생하면 뒤에 이어지는 then() 등이 전부 영향을 받는다
        // 그러므로 value 를 잘 넘겨받아 data 를 처리할 수 있도록 error 에 대해 return 으로 value 를 넘겨줘야한다

        getHen().then(getEgg).then(getCook).then(console.log);
    </script>
  </body>
</html>
